include ./themes/rose-pine/dist/rose-pine.conf

# Font
font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto

font_size 13.0

# Window layout
remember_window_size no
initial_window_width 80c
initial_window_height 25c
window_padding_width 5

