%if #{m/ri:(kitty|alacritty),#{TERM_PROGRAM}#{COLORTERM}#{TERM}}
    set -g default-terminal "tmux-256color"
%else
    set -g default-terminal "xterm-256color"
%endif

set -as terminal-features ",${TERM}:RGB"
set -as terminal-features ",${TERM}:Tc"

set -g pane-border-style fg=default,bg=default
set -g pane-active-border-style fg=default,bg=default

setw -g mode-keys vi

set -g destroy-unattached on

set -s set-clipboard on

# For Neovim
set -g focus-events on

