%if #{m/ri:(kitty|alacritty),#{TERM_PROGRAM}#{COLORTERM}#{TERM}}
    set -g default-terminal "tmux-256color"
%else
    set -g default-terminal "${TERM}"
%endif

set -as terminal-features ",${TERM}:RGB"
set -as terminal-features ",${TERM}:Tc"

setw -g mode-keys vi

set -g destroy-unattached on

# For Neovim
set -g focus-events on

