[general]
import = ["themes/rose-pine/dist/rose-pine.toml"]
live_config_reload = true

[window]
dynamic_padding = true
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 13

[selection]
save_to_clipboard = true

